document.write("<div style='width: 792px;' id='topnavi'>")
document.write("<div>")
document.write("<ul>")
  document.write("<li style='width: 142px;' class='selected'><a href='acs_support.html' >ACS Cases</a></li>")
  document.write("<li style='width: 122px;' class='selected'><a href='bankruptcy.html' >Bankruptcy</a></li>")
  document.write("<li style='width: 122px;' class='selected'><a href='matrimonial.html' >Divorce</a></li>")
  document.write("<li style='width: 132px;' class='selected'><a href='familylaw.html' >Family Law</a></li>")
  document.write("<li style='width: 142px;' class='selected'><a href='estateplanning.html' >Wills &amp; Estates</a></li>")
  document.write("<li style='width: 132px;' class='selected'><a href='contact.html' >Contact Us</a></li>")
  document.write("</ul>")
document.write("</div>")
document.write("</div>")
